### ISSUE TITLE
Add PyCardano based Fortuna Miner

### ISSUE THREAD

**Issue by nielstron** [B3nac/awesome-pycardano#1]
https://github.com/nielstron/python-fortuna-miner/

Note: I never managed to mine with this because it became just too hard :/

**Comment by B3nac** [comment]
Note: still awesome, approved!

**Comment by B3nac** [comment]
Added in this commit [f1c763b](https://github.com/B3nac/awesome-pycardano/commit/f1c763b79ff0275c5e44b400b399605070d60fa5) :beers:
